#!/usr/bin/env python3
"""Regenerate migrations/0002_seed_products.sql from the dummyjson payload.

The payload in seed/ is the source of truth and is committed, so seeding is
reproducible without network access:

    curl -s "https://dummyjson.com/products?limit=0&select=$FIELDS" \
        -o seed/dummyjson-products.json
    python3 scripts/generate-seed-sql.py
"""

import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "seed" / "dummyjson-products.json"
OUT = ROOT / "migrations" / "0002_seed_products.sql"

COLUMNS = [
    "id", "slug", "title", "category", "description", "price_cents",
    "discount_pct", "rating", "stock", "availability", "brand", "sku",
    "weight_grams", "width_mm", "height_mm", "depth_mm", "warranty",
    "shipping", "return_policy", "min_order", "thumbnail_url", "tags",
]


def slugify(title, taken):
    base = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-") or "product"
    slug = base
    n = 2
    while slug in taken:
        slug = f"{base}-{n}"
        n += 1
    taken.add(slug)
    return slug


def lit(value):
    if value is None or value == "":
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, list):
        if not value:
            return "'{}'"
        return "array[" + ", ".join(lit(v) for v in value) + "]"
    return "'" + str(value).replace("'", "''") + "'"


def main():
    products = json.loads(SRC.read_text())["products"]
    taken = set()
    rows = []
    for p in products:
        dim = p.get("dimensions") or {}
        rows.append([
            p["id"],
            slugify(p["title"], taken),
            p["title"],
            p["category"],
            p.get("description") or "",
            round(p["price"] * 100),
            p.get("discountPercentage") or 0,
            p.get("rating"),
            p.get("stock") or 0,
            p.get("availabilityStatus") or "Unknown",
            p.get("brand"),
            p.get("sku"),
            p.get("weight"),
            dim.get("width"),
            dim.get("height"),
            dim.get("depth"),
            p.get("warrantyInformation"),
            p.get("shippingInformation"),
            p.get("returnPolicy"),
            p.get("minimumOrderQuantity"),
            p.get("thumbnail"),
            p.get("tags") or [],
        ])

    lines = [
        "-- Generated by scripts/generate-seed-sql.py from",
        "-- seed/dummyjson-products.json (https://dummyjson.com/products).",
        "-- Edit the generator or the payload, not this file.",
        "",
        f"insert into products ({', '.join(COLUMNS)}) values",
    ]
    values = [f"    ({', '.join(lit(v) for v in row)})" for row in rows]
    lines.append(",\n".join(values))
    lines.append("on conflict (id) do nothing;")
    lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)} — {len(rows)} products")


if __name__ == "__main__":
    main()
